ignoreWorkspaceRootCheck: true
shamefullyHoist: true
shellEmulator: true
trustPolicy: no-downgrade

packages:
  - playground
  - examples/*

update:
  ignoreDeps:
    - typescript@7

overrides:
  chokidar: ^5.0.0
  eslint: ^10.9.1
  eslint-plugin-antfu: 'workspace:*'

allowBuilds:
  esbuild: true
  simple-git-hooks: true
